
export const AIGIS_PREF_NAME = 'aigis-pref';

export const PREF_KEY_SECRETS  = 'secrets';
export const PREF_KEY_ITEMS    = 'items';
export const PREF_KEY_SETTINGS = 'settings';
export const PREF_MASTER_KEY   = 'master-key';
export const PREF_DEC_MASTER_KEY = 'dec-master-key';
export const PREF_PASSWORD_CHALLENGE_TIME = 'password-challenge-timestamp';
export const ONE_DAY_IN_MS = 24*60*60*1000;

export const PREF_ICON_PACKS   = 'icon-packs';
export const MAX_ICON_PACK_NUM = 5;
export const MAX_ICON_PACK_SIZE = 5*1024*1024;//5MB

export const FAKE_OTP_CODE = '******';
export const ATL1_MAX_REUSE_DURATION = 5*1000;//5s
export const ATL3_MAX_REUSE_DURATION = 5*1000;//5s
export const ATL1_AUTH_TIMEOUT = 90*1000;//90s
export const ATL3_AUTH_TIMEOUT = 90*1000;//90s

export const OFFICIAL_WEBSITE = 'https://github.com/iamhyc/Aigis';
export const FEEDBACK_WEBSITE = 'https://github.com/iamhyc/Aigis/issues/new';
