
export const AIGIS_PREF_NAME = 'aigis-pref';

export const PREF_KEY_SECRETS  = 'secrets';
export const PREF_KEY_ITEMS    = 'items';
export const PREF_KEY_SETTINGS = 'settings';
export const PREF_MASTER_KEY   = 'master-key';

export const FAKE_OTP_CODE = '******';

export const OFFICIAL_WEBSITE = 'https://github.com/iamhyc/Aigis';
export const FEEDBACK_WEBSITE = 'https://github.com/iamhyc/Aigis/issues/new';
